
  0%|                                                                                                                                       | 0/39 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/data/home/ubuntu/workspace/dacon/src/weather_rain_res101.py", line 259, in <module>
    infer_model = train(model,
  File "/data/home/ubuntu/workspace/dacon/src/weather_rain_res101.py", line 119, in train
    loss.backward()
  File "/data/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/home/ubuntu/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`